name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build-all-examples:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1
      - name: Build
        run: zig build
        working-directory: examples
